### ISSUE TITLE
publish it in official repo

### ISSUE THREAD

**Issue by GETandSELECT** [oscaropenness/plugin.video.heiseshowrss#1]
Hi

thanks for your effort

when you will publish it in official repo?

**Comment by oscaropenness** [comment]
This is on my todo list. Hopefully I will find time in the next few days.

**Comment by oscaropenness** [comment]
It is official now. You can find it as **#Heiseshow HD**.

**Comment by GETandSELECT** [comment]
Thank you.
Working fine.
